name: Main

on: 
  push:
  # schedule:
  #   - cron: '0 2 * * *'

env:
  BUILD_FOLDER: build

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:

    - name: Checkout ezc3d main
      uses: actions/checkout@v4
      with:
         repository: pyomeca/ezc3d
         path: 'ezc3d'

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install numpy and scikit-build
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel numpy==1.26 scikit-build


    # - name: Install Git
    #   run: choco install git

    # - name: Install CMake
    #   run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    # - name: Install SWIG
    #   run: choco install swig

    # - name: List Choco
    #   run: choco list    


    - name: Build ezc3d on WINDOWS
      run: |
        # echo ~/build
        # mkdir ~/build
        # mkdir ~/ezc3d_python
        # cmake $env:GITHUB_WORKSPACE/ezc3d -G"Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX=~/build -DPYTHON_INSTALL_PREFIX=~/build/ezc3d_python -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_DOC=OFF -DBUILD_EXAMPLE=OFF -DUSE_MATRIX_FAST_ACCESSOR=OFF -DBINDER_MATLAB=OFF -DBINDER_PYTHON3=ON
        # cmake --build . --config Release --target install -- /maxcpucount:4
        # dir ~/build

        chdir $env:GITHUB_WORKSPACE/ezc3d
        python setup.py sdist bdist_wheel --dist-dir ~/ezc3d_python -- -G"Visual Studio 17 2022" -A x64

        dir $env:GITHUB_WORKSPACE/ezc3d
        dir $env:GITHUB_WORKSPACE/ezc3d/dist


    - name: Upload ezc3d
      uses: actions/upload-artifact@v4
      with:
        name: ezc3d-win-py312
        # path: ~/build
        # path: D:\a\testBuildEZC3D\testBuildEZC3D\ezc3d\dist
        path: ~/ezc3d_python/*.whl
