name: Main

on: 
  push:
  # schedule:
  #   - cron: '0 2 * * *'

env:
  BUILD_FOLDER: build

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:

    - name: Checkout ezc3d main
      uses: actions/checkout@v4
      with:
         repository: pyomeca/ezc3d
         path: 'ezc3d'

    - name: Check files
      run: |
        D:
        cd D:\a\testBuildEZC3D\testBuildEZC3D\ezc3d
        dir

    # - name: Install Git
    #   run: choco install git

    # - name: Install CMake
    #   run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Install SWIG
      run: |
        choco install swig
        # choco install swig --yes --limit-output --allow-downgrade
        # swig -swiglib
      
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install NumPy 
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        python -m pip install numpy==1.26

    - name: Build ezc3d on WINDOWS
      run: |
        echo  $env:GITHUB_WORKSPACE\\build
        mkdir $env:GITHUB_WORKSPACE\\build
        chdir $env:GITHUB_WORKSPACE\\build
        cmake $env:GITHUB_WORKSPACE/ezc3d -G"Visual Studio 17 2022" -Ax64 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_DOC=OFF -DBUILD_EXAMPLE=OFF -DUSE_MATRIX_FAST_ACCESSOR=OFF -DBINDER_MATLAB=OFF -DBINDER_PYTHON3=ON
        cmake --build . --config Release --target install -- /maxcpucount:4

    - name: Check files
      run: |
        cd
        dir

    - name: Upload ezc3d
      uses: actions/upload-artifact@v4
      with:
        name: ezc3d-win-py312
        path: $env:GITHUB_WORKSPACE\\build