name: Main

on: 
  push:
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  windows:
    name: Windows

    runs-on: windows-latest

    steps:

    - name: Install Python packages
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Checkout ezc3d main
      uses: actions/checkout@v4
      with:
         repository: pyomeca/ezc3d
         path: 'ezc3d'

    - name: Build ezc3d on WINDOWS
      run: |
        MAIN_FOLDER=`pwd`
        CONDA_ENV_PATH=$CONDA/envs/ezc3d
        mkdir -p $BUILD_FOLDER
        cd $BUILD_FOLDER
        cmake -G"Visual Studio 17 2022" -Ax64 -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_DOC=OFF -DBUILD_EXAMPLE=OFF -DUSE_MATRIX_FAST_ACCESSOR=OFF -DBINDER_MATLAB=ON -DMatlab_ezc3d_INSTALL_DIR=$HOME -DBINDER_PYTHON3=ON ..
        cmake --build . --config Release --target install -j${{ steps.cpu-cores.outputs.count }}
        cd $MAIN_FOLDER

    - name: Install dependencies
      run: |
        cd
        dir

    - name: Upload ezc3d
      uses: actions/upload-artifact@v4
      with:
        name: ezc3d-win-py312
        path: dist/*.whl