name: Main

on: 
  push:
  # schedule:
  #   - cron: '0 2 * * *'

env:
  BUILD_FOLDER: build

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:

    - name: Checkout ezc3d main
      uses: actions/checkout@v4
      with:
         repository: pyomeca/ezc3d
         path: 'ezc3d'

    - name: Check files
      run: |
        D:
        cd D:\a\testBuildEZC3D\testBuildEZC3D\ezc3d
        dir

    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores

    # - name: Install SWIG
    #   run: |
    #     choco install swig --yes --limit-output --allow-downgrade
    #     swig -swiglib
      
    # - name: Install Python packages
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.12'
        
    # - name: Install NumPy 
    #   run: python3 -m pip install numpy==1.26

    - name: Setup environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        # miniforge-variant: Mambaforge
        miniforge-version: latest
        python-version: '3.12'
        # use-mamba: true
        # environment-file: environment.yml
      
    - name: Print conda info
      run: |
        conda info
        conda list
        
    - name: Install dependencies
      run: |
        conda install -c conda-forge cmake git pkgconfig
        conda list
        git submodule update --init --recursive

    - name: Build ezc3d on WINDOWS
      run: |
        MAIN_FOLDER=`pwd`
        CONDA_ENV_PATH=$CONDA/envs/ezc3d
        mkdir -p $BUILD_FOLDER
        cd $BUILD_FOLDER
        cmake -G"Visual Studio 17 2022" -Ax64 -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_DOC=OFF -DBUILD_EXAMPLE=OFF -DUSE_MATRIX_FAST_ACCESSOR=OFF -DBINDER_MATLAB=OFF -DBINDER_PYTHON3=ON ..
        cmake --build . --config Release --target install -j${{ steps.cpu-cores.outputs.count }}
        cd $MAIN_FOLDER

    - name: Check files
      run: |
        cd
        dir

    - name: Upload ezc3d
      uses: actions/upload-artifact@v4
      with:
        name: ezc3d-win-py312
        path: dist/*.whl